# Generated by Django 5.1.2 on 2025-11-14 15:08

import django.db.models.deletion
from django.db import migrations, models


def create_default_wage_types(apps, schema_editor):
    WageType = apps.get_model('adealohn', 'WageType')
    defaults = [
        ("GRUNDLOHN_MONAT", "Grundlohn Monatslohn", "GRUNDLOHN"),
        ("GRUNDLOHN_STUNDEN", "Grundlohn Stundenlohn", "GRUNDLOHN"),
        ("ZULAGE_NACHT", "Nachtzulage", "ZULAGE"),
        ("ZULAGE_SCHICHT", "Schichtzulage", "ZULAGE"),
        ("FAMILIENZULAGE", "Familienzulage", "FAMILIENZULAGE"),
        ("SPESEN_EFFEKTIV", "Spesen effektiv", "SPESEN"),
        ("PRIVATANTEIL_AUTO", "Privatanteil Auto", "SACHLEISTUNG"),
        ("PRIVATANTEIL_TELEFON", "Privatanteil Telefon", "SACHLEISTUNG"),
    ]
    for code, name, category in defaults:
        WageType.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "category": category,
            },
        )


def remove_default_wage_types(apps, schema_editor):
    WageType = apps.get_model('adealohn', 'WageType')
    WageType.objects.filter(
        code__in=[
            "GRUNDLOHN_MONAT",
            "GRUNDLOHN_STUNDEN",
            "ZULAGE_NACHT",
            "ZULAGE_SCHICHT",
            "FAMILIENZULAGE",
            "SPESEN_EFFEKTIV",
            "PRIVATANTEIL_AUTO",
            "PRIVATANTEIL_TELEFON",
        ]
    ).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adeacore', '0002_payrollrecord_ahv_basis_payrollrecord_alv_basis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('GRUNDLOHN', 'Grundlohn'), ('ZULAGE', 'Zulage'), ('FAMILIENZULAGE', 'Familienzuschlag'), ('SPESEN', 'Spesen'), ('SACHLEISTUNG', 'Sachleistung'), ('KORREKTUR', 'Korrektur'), ('SONSTIGES', 'Sonstiges')], default='GRUNDLOHN', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_lohnwirksam', models.BooleanField(default=True)),
                ('ahv_relevant', models.BooleanField(default=True)),
                ('alv_relevant', models.BooleanField(default=True)),
                ('bvg_relevant', models.BooleanField(default=True)),
                ('uv_relevant', models.BooleanField(default=True)),
                ('qst_relevant', models.BooleanField(default=True)),
                ('taxable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Betrag pro Einheit oder Gesamtbetrag, je nach Lohnart.', max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adeacore.payrollrecord')),
                ('wage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='adealohn.wagetype')),
            ],
            options={
                'ordering': ['payroll_id', 'wage_type__code'],
            },
        ),
        migrations.RunPython(create_default_wage_types, remove_default_wage_types),
    ]
