# Generated by Django 5.1.2 on 2025-11-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adealohn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KTGParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktg_rate_employee', models.DecimalField(decimal_places=4, default=0, help_text='KTG-Beitragssatz Arbeitnehmer (z.B. 0.0150 für 1.5%)', max_digits=5)),
                ('ktg_rate_employer', models.DecimalField(decimal_places=4, default=0, help_text='KTG-Beitragssatz Arbeitgeber (z.B. 0.0150 für 1.5%)', max_digits=5)),
                ('ktg_max_basis', models.DecimalField(blank=True, decimal_places=2, help_text='Maximale Bemessungsgrundlage (z.B. 148200.00 für Jahreslohn). Optional.', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'KTG Parameter',
                'verbose_name_plural': 'KTG Parameter',
            },
        ),
    ]
