# Generated by Django 5.1.2 on 2025-11-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adealohn', '0002_ktgparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BVGParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025, help_text='Jahr für diese BVG-Parameter', unique=True)),
                ('entry_threshold', models.DecimalField(decimal_places=2, help_text='Eintrittsschwelle (Jahreslohn, unterhalb keine BVG-Pflicht)', max_digits=10)),
                ('coordination_deduction', models.DecimalField(decimal_places=2, help_text='Koordinationsabzug (jährlich)', max_digits=10)),
                ('min_insured_salary', models.DecimalField(decimal_places=2, help_text='Minimum versicherter Lohn (jährlich)', max_digits=10)),
                ('max_insured_salary', models.DecimalField(decimal_places=2, help_text='Maximum versicherter Lohn (jährlich)', max_digits=10)),
                ('employee_rate', models.DecimalField(decimal_places=4, help_text='BVG-Beitragssatz Arbeitnehmer (z.B. 0.0500 für 5%)', max_digits=5)),
                ('employer_rate', models.DecimalField(decimal_places=4, help_text='BVG-Beitragssatz Arbeitgeber (z.B. 0.0500 für 5%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'BVG Parameter',
                'verbose_name_plural': 'BVG Parameter',
                'ordering': ['-year'],
            },
        ),
    ]
