# Generated by Django 5.1.2 on 2025-11-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adealohn', '0003_bvgparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='QSTParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Jahr für diese QST-Parameter')),
                ('tarif', models.CharField(help_text="QST-Tarif (z.B. 'A', 'B', 'C')", max_length=5)),
                ('prozent', models.DecimalField(blank=True, decimal_places=2, help_text='QST-Prozentsatz (z.B. 5.00 für 5%)', max_digits=5, null=True)),
                ('fixbetrag', models.DecimalField(blank=True, decimal_places=2, help_text='QST-Fixbetrag (hat Vorrang vor Prozentsatz)', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'QST Parameter',
                'verbose_name_plural': 'QST Parameter',
                'ordering': ['-year', 'tarif'],
                'unique_together': {('year', 'tarif')},
            },
        ),
    ]
