# Generated by Django 5.1.2 on 2025-11-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adealohn', '0004_qstparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyAllowanceParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Jahr für diese Familienzulagen-Parameter', unique=True)),
                ('kinderzulage_betrag', models.DecimalField(decimal_places=2, help_text='Jährlicher Betrag pro Kind (Kinderzulage) in CHF', max_digits=10)),
                ('ausbildungszulage_betrag', models.DecimalField(decimal_places=2, help_text='Jährlicher Betrag pro Kind in Ausbildung (Ausbildungszulage) in CHF', max_digits=10)),
                ('monatlich_kinderzulage', models.DecimalField(decimal_places=2, editable=False, help_text='Monatlicher Betrag pro Kind (Kinderzulage) in CHF (wird automatisch berechnet: jährlich / 12)', max_digits=10)),
                ('monatlich_ausbildungszulage', models.DecimalField(decimal_places=2, editable=False, help_text='Monatlicher Betrag pro Kind in Ausbildung (Ausbildungszulage) in CHF (wird automatisch berechnet: jährlich / 12)', max_digits=10)),
            ],
            options={
                'verbose_name': 'Familienzulagen Parameter',
                'verbose_name_plural': 'Familienzulagen Parameter',
                'ordering': ['-year'],
            },
        ),
        migrations.AlterField(
            model_name='qstparameter',
            name='tarif',
            field=models.CharField(help_text="QST-Tarif im Format [Familienstand][Kinder][Kirchensteuer], z.B. 'A0N' (alleinstehend, 0 Kinder, ohne Kirche), 'A0Y' (mit Kirche), 'B1N' (verheiratet, 1 Kind, ohne Kirche), 'B1Y' (mit Kirche). Familienstand: A=alleinstehend, B=verheiratet. Kirchensteuer: N=nein, Y=ja.", max_length=5),
        ),
    ]
