# Generated by Django 5.1.2 on 2025-12-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adealohn', '0008_add_privatanteil_wage_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagetype',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
