# Generated by Django 5.1.2 on 2025-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adealohn', '0009_alter_wagetype_code'),
    ]

    operations = [
        # Migration 0009 hat bereits max_length=50 gesetzt
        # Diese Migration ist redundant, aber wird für Konsistenz beibehalten
        migrations.AlterField(
            model_name='wagetype',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
