# Generated by Django 5.2.10 on 2026-02-02 16:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adealohn', '0010_alter_wagetype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UVGParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025, help_text='Jahr für diese UVG-Parameter', unique=True)),
                ('bu_rate_employer', models.DecimalField(decimal_places=4, default=Decimal('0.00644'), help_text='BU-Beitragssatz Arbeitgeber (z.B. 0.00644 für 0.644%)', max_digits=5)),
                ('nbu_rate_employee', models.DecimalField(decimal_places=4, default=Decimal('0.0230'), help_text='NBU-Beitragssatz Arbeitnehmer (z.B. 0.0230 für 2.3%)', max_digits=5)),
                ('max_annual_insured_salary', models.DecimalField(decimal_places=2, default=Decimal('148200.00'), help_text="Maximal versichertes Jahreseinkommen (Standard: 148'200 CHF)", max_digits=10)),
            ],
            options={
                'verbose_name': 'UVG Parameter',
                'verbose_name_plural': 'UVG Parameter',
                'ordering': ['-year'],
            },
        ),
    ]
