# Generated by Django 5.2.10 on 2026-02-02 16:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adealohn', '0011_add_uvg_parameter_fak_vk_vacation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAKParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, help_text='Jahr für diese FAK-Parameter')),
                ('canton', models.CharField(help_text="Kanton (z.B. 'AG', 'ZH', 'BE') oder 'DEFAULT' für Standard", max_length=50)),
                ('fak_rate_employer', models.DecimalField(decimal_places=4, default=Decimal('0.01025'), help_text='FAK-Beitragssatz Arbeitgeber (z.B. 0.01450 für 1.450%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'FAK Parameter',
                'verbose_name_plural': 'FAK Parameter',
                'ordering': ['-year', 'canton'],
                'unique_together': {('year', 'canton')},
            },
        ),
    ]
