# Generated by Django 5.2.10 on 2026-02-02 16:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adealohn', '0012_add_fak_parameter_canton_work_canton'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHVParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025, help_text='Jahr für diese AHV-Parameter', unique=True)),
                ('rate_employee', models.DecimalField(decimal_places=4, default=Decimal('0.053'), help_text='AHV-Beitragssatz Arbeitnehmer (z.B. 0.0530 für 5.3%)', max_digits=5)),
                ('rate_employer', models.DecimalField(decimal_places=4, default=Decimal('0.053'), help_text='AHV-Beitragssatz Arbeitgeber (z.B. 0.0530 für 5.3%)', max_digits=5)),
                ('rentner_freibetrag_monat', models.DecimalField(decimal_places=2, default=Decimal('1400.00'), help_text="Rentnerfreibetrag pro Monat (Standard: 1'400 CHF)", max_digits=10)),
            ],
            options={
                'verbose_name': 'AHV Parameter',
                'verbose_name_plural': 'AHV Parameter',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ALVParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025, help_text='Jahr für diese ALV-Parameter', unique=True)),
                ('rate_employee', models.DecimalField(decimal_places=4, default=Decimal('0.011'), help_text='ALV-Beitragssatz Arbeitnehmer (z.B. 0.0110 für 1.1%)', max_digits=5)),
                ('rate_employer', models.DecimalField(decimal_places=4, default=Decimal('0.011'), help_text='ALV-Beitragssatz Arbeitgeber (z.B. 0.0110 für 1.1%)', max_digits=5)),
                ('max_annual_insured_salary', models.DecimalField(decimal_places=2, default=Decimal('148200.00'), help_text="Maximal versichertes Jahreseinkommen (Standard: 148'200 CHF)", max_digits=10)),
            ],
            options={
                'verbose_name': 'ALV Parameter',
                'verbose_name_plural': 'ALV Parameter',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='VKParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025, help_text='Jahr für diese VK-Parameter', unique=True)),
                ('rate_employer', models.DecimalField(decimal_places=4, default=Decimal('0.03'), help_text='VK-Beitragssatz Arbeitgeber (in % des Total AHV-Beitrags, z.B. 0.03 für 3.0%). Aktueller Satz kann auf AHV-Rechnung gefunden werden.', max_digits=5)),
            ],
            options={
                'verbose_name': 'VK Parameter',
                'verbose_name_plural': 'VK Parameter',
                'ordering': ['-year'],
            },
        ),
        migrations.AlterModelOptions(
            name='ktgparameter',
            options={'ordering': ['-year'], 'verbose_name': 'KTG Parameter', 'verbose_name_plural': 'KTG Parameter'},
        ),
        migrations.AddField(
            model_name='ktgparameter',
            name='year',
            field=models.IntegerField(default=2025, help_text='Jahr für diese KTG-Parameter', unique=True),
        ),
        migrations.AlterField(
            model_name='fakparameter',
            name='fak_rate_employer',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), help_text='FAK-Beitragssatz Arbeitgeber (z.B. 0.01 für 1.0% Standard, 0.01450 für 1.450% Aargau). Aktueller Satz kann auf AHV-Rechnung gefunden werden.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ktgparameter',
            name='ktg_max_basis',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximale Bemessungsgrundlage (z.B. 300000.00 für Jahreslohn). Optional.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ktgparameter',
            name='ktg_rate_employee',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.005'), help_text='KTG-Beitragssatz Arbeitnehmer (z.B. 0.0050 für 0.5%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ktgparameter',
            name='ktg_rate_employer',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.005'), help_text='KTG-Beitragssatz Arbeitgeber (z.B. 0.0050 für 0.5%)', max_digits=5),
        ),
    ]
