# Generated by Django 5.1.2 on 2025-11-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='ahv_basis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='alv_basis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='bvg_basis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='qst_basis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='uv_basis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
