# Generated by Django 5.1.2 on 2025-11-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0002_payrollrecord_ahv_basis_payrollrecord_alv_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ahv_freibetrag_aktiv',
            field=models.BooleanField(default=True, help_text='Rentnerfreibetrag 1400/Monat anwenden'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_rentner',
            field=models.BooleanField(default=False, help_text='Ist der Mitarbeiter Rentner?'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='ahv_effective_basis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='ahv_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='ahv_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
