# Generated by Django 5.1.2 on 2025-11-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0003_employee_ahv_freibetrag_aktiv_employee_is_rentner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='alv_effective_basis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='alv_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='alv_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
