# Generated by Django 5.1.2 on 2025-11-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0004_payrollrecord_alv_effective_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nbu_pflichtig',
            field=models.BooleanField(default=False, help_text='NBU-Pflicht (AN). Automatisch bei >8h/Woche, aber manuell überschreibbar.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_hours',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Wöchentliche Arbeitsstunden', max_digits=4),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='bu_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='bu_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='nbu_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='uvg_effective_basis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
