# Generated by Django 5.1.2 on 2025-11-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0005_employee_nbu_pflichtig_employee_weekly_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='ktg_effective_basis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='ktg_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='ktg_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
