# Generated by Django 5.1.2 on 2025-11-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0006_payrollrecord_ktg_effective_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='bvg_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='bvg_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='bvg_insured_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
