# Generated by Django 5.1.2 on 2025-11-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0007_payrollrecord_bvg_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='qst_fixbetrag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='QST-Fixbetrag (hat Vorrang vor Prozentsatz)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='qst_kinder',
            field=models.PositiveIntegerField(default=0, help_text='Anzahl Kinder für QST-Berechnung'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qst_kirchensteuer',
            field=models.BooleanField(default=False, help_text='Kirchensteuerpflichtig'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qst_pflichtig',
            field=models.BooleanField(default=False, help_text='Quellensteuerpflichtig'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qst_prozent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='QST-Prozentsatz (z.B. 5.00 für 5%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='qst_tarif',
            field=models.CharField(blank=True, help_text="QST-Tarif (z.B. 'A', 'B', 'C')", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='qst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
