# Generated by Django 5.1.2 on 2025-11-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0008_employee_qst_fixbetrag_employee_qst_kinder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='qst_kirchensteuer',
            field=models.BooleanField(default=False, help_text='Kirchensteuerpflichtig (wird in qst_effective_tarif kodiert, z.B. A0Y statt A0N)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qst_tarif',
            field=models.CharField(blank=True, help_text="QST-Tarif: Familienstand (A=alleinstehend, B=verheiratet) oder vollständig (z.B. 'A0N', 'B1Y'). Vollständiges Format: [Familienstand][Kinder][Kirchensteuer] mit N=ohne, Y=mit Kirche. Wenn nur Familienstand angegeben, wird Tarif automatisch aus Kindern und Kirchensteuer ergänzt.", max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='SVAEntscheid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entscheid', models.CharField(help_text="Entscheid-Nummer oder Beschreibung (z.B. 'FAK-2025-12345')", max_length=255)),
                ('von_datum', models.DateField(help_text='Gültigkeitsbeginn des Entscheids')),
                ('bis_datum', models.DateField(blank=True, help_text='Gültigkeitsende des Entscheids (optional, leer = unbefristet)', null=True)),
                ('betrag_monatlich', models.DecimalField(decimal_places=2, help_text='Monatlicher Betrag der Familienzulage in CHF', max_digits=10)),
                ('beschreibung', models.TextField(blank=True, help_text='Zusätzliche Informationen zum Entscheid (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Mitarbeiter, für den dieser SVA-Entscheid gilt', on_delete=django.db.models.deletion.CASCADE, related_name='sva_entscheide', to='adeacore.employee')),
            ],
            options={
                'verbose_name': 'SVA-Entscheid',
                'verbose_name_plural': 'SVA-Entscheide',
                'ordering': ['-von_datum', 'employee__last_name'],
            },
        ),
    ]
