# Generated by Django 5.1.2 on 2025-11-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0009_add_sva_entscheid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='status',
            field=models.CharField(choices=[('ENTWURF', 'Entwurf'), ('GEPRUEFT', 'Geprüft'), ('ABGERECHNET', 'Abgerechnet'), ('GESPERRT', 'Gesperrt')], default='ENTWURF', help_text='Status des Lohnlaufs. Gesperrte Löhne können nicht mehr bearbeitet werden.', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together={('employee', 'month', 'year')},
        ),
    ]
