# Generated by Django 5.1.2 on 2025-11-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0010_add_payroll_record_status_and_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='alv_ytd_basis',
            field=models.DecimalField(decimal_places=2, default=0, help_text="ALV YTD-Basis (Year-to-Date) für Kappung bei 148'200 CHF/Jahr", max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='bvg_ytd_basis',
            field=models.DecimalField(decimal_places=2, default=0, help_text='BVG YTD-Basis (Year-to-Date) für Jahreslohnberechnung', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='bvg_ytd_insured_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='BVG YTD versicherter Lohn (Year-to-Date) für monatliche Berechnung', max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='uvg_ytd_basis',
            field=models.DecimalField(decimal_places=2, default=0, help_text="UVG YTD-Basis (Year-to-Date) für Kappung bei 148'200 CHF/Jahr", max_digits=10),
        ),
    ]
