# Generated by Django 5.1.2 on 2025-11-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0011_add_ytd_fields_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('FIRMA', 'Firma'), ('PRIVAT', 'Privatperson')], default='FIRMA', help_text='Mandantentyp: Firma (für Lohnbuchhaltung) oder Privatperson (nur für Zeiterfassung)', max_length=10),
        ),
    ]
