# Generated by Django 5.1.2 on 2025-11-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0012_add_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='geburtsdatum',
            field=models.DateField(blank=True, help_text='Geburtsdatum (nur PRIVAT)', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='interne_notizen',
            field=models.TextField(blank=True, help_text='Interne Notizen und Bemerkungen'),
        ),
        migrations.AddField(
            model_name='client',
            name='kontaktperson_name',
            field=models.CharField(blank=True, help_text='Name der Kontaktperson (für FIRMA)', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='mwst_nr',
            field=models.CharField(blank=True, help_text='MWST-Nummer (nur FIRMA)', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='mwst_pflichtig',
            field=models.BooleanField(default=False, help_text='Ist der Mandant MWST-pflichtig? (nur FIRMA)'),
        ),
        migrations.AddField(
            model_name='client',
            name='rechnungs_email',
            field=models.EmailField(blank=True, help_text='E-Mail-Adresse für Rechnungen (nur FIRMA)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='steuerkanton',
            field=models.CharField(blank=True, help_text='Steuerkanton (nur PRIVAT)', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='zahlungsziel_tage',
            field=models.PositiveIntegerField(default=30, help_text='Zahlungsziel in Tagen (nur FIRMA)'),
        ),
    ]
