# Generated by Django 5.1.2 on 2025-11-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0013_add_client_fields_mwst_steuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lohn_aktiv',
            field=models.BooleanField(default=False, help_text='Aktiviert die Lohnbuchhaltung (AdeaLohn) für diesen Mandanten. Nur bei FIRMA-Mandanten relevant.'),
        ),
    ]
