# Generated by Django 5.1.2 on 2025-11-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0014_add_lohn_aktiv_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('FIRMA', 'Firma'), ('PRIVAT', 'Privatperson')], default='FIRMA', help_text='Mandantentyp: Firma (für Lohnbuchhaltung) oder Privatperson (nur für Zeiterfassung)', max_length=10, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='geburtsdatum',
            field=models.DateField(blank=True, help_text='Geburtsdatum (nur PRIVAT)', null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='client',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hausnummer'),
        ),
        migrations.AlterField(
            model_name='client',
            name='interne_notizen',
            field=models.TextField(blank=True, help_text='Interne Notizen und Bemerkungen', verbose_name='Interne Notizen'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kontaktperson_name',
            field=models.CharField(blank=True, help_text='Name der Kontaktperson (für FIRMA)', max_length=255, verbose_name='Kontaktperson'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lohn_aktiv',
            field=models.BooleanField(default=False, help_text='Aktiviert die Lohnbuchhaltung (AdeaLohn) für diesen Mandanten. Nur bei FIRMA-Mandanten relevant.', verbose_name='AdeaLohn aktiviert'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mwst_nr',
            field=models.CharField(blank=True, help_text='MWST-Nummer (nur FIRMA)', max_length=50, verbose_name='MWST-Nummer'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mwst_pflichtig',
            field=models.BooleanField(default=False, help_text='Ist der Mandant MWST-pflichtig? (nur FIRMA)', verbose_name='MWST-pflichtig'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rechnungs_email',
            field=models.EmailField(blank=True, help_text='E-Mail-Adresse für Rechnungen (nur FIRMA)', max_length=254, null=True, verbose_name='Rechnungs-E-Mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='steuerkanton',
            field=models.CharField(blank=True, help_text='Steuerkanton (nur PRIVAT)', max_length=50, verbose_name='Steuerkanton'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Strasse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='uid',
            field=models.CharField(blank=True, max_length=100, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zahlungsziel_tage',
            field=models.PositiveIntegerField(default=30, help_text='Zahlungsziel in Tagen (nur FIRMA)', verbose_name='Zahlungsziel (Tage)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='PLZ'),
        ),
    ]
