# Generated by Django 5.1.2 on 2025-11-20 13:35

from django.db import migrations, models


def migrate_uid_to_mwst_nr(apps, schema_editor):
    """Migriert vorhandene UID-Werte zu mwst_nr, falls mwst_nr leer ist."""
    Client = apps.get_model('adeacore', 'Client')
    for client in Client.objects.all():
        # Wenn mwst_nr leer ist, aber uid vorhanden → kopiere uid nach mwst_nr
        if not client.mwst_nr and client.uid:
            client.mwst_nr = client.uid
            client.save()


def reverse_migrate(apps, schema_editor):
    """Reverse: Kopiere mwst_nr zurück zu uid (falls nötig)."""
    Client = apps.get_model('adeacore', 'Client')
    for client in Client.objects.all():
        if client.mwst_nr:
            # uid wird als Property zurückgegeben, daher keine Aktion nötig
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0015_add_german_verbose_names'),
    ]

    operations = [
        # Daten migrieren BEVOR das Feld entfernt wird
        migrations.RunPython(migrate_uid_to_mwst_nr, reverse_migrate),
        # Feld entfernen
        migrations.RemoveField(
            model_name='client',
            name='uid',
        ),
        # mwst_nr Label aktualisieren
        migrations.AlterField(
            model_name='client',
            name='mwst_nr',
            field=models.CharField(blank=True, help_text='MWST-Nummer / UID (in CH identisch, nur FIRMA)', max_length=50, verbose_name='MWST-Nummer / UID'),
        ),
    ]
