# Generated by Django 5.1.2 on 2025-11-26 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0016_remove_uid_field_use_mwst_nr'),
        ('adeazeit', '0013_add_sachbearbeiter_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sachbearbeiter',
            field=models.ForeignKey(blank=True, help_text='Sachbearbeiter, der für diesen Mandanten Zugriff auf AdeaLohn hat. Nur bei FIRMA-Mandanten mit aktiviertem Lohnmodul relevant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lohn_clients', to='adeazeit.employeeinternal', verbose_name='Sachbearbeiter (AdeaLohn)'),
        ),
    ]
