# Generated by Django 5.1.2 on 2025-11-26 13:40

import adeacore.fields
from django.db import migrations, models


def encrypt_existing_data(apps, schema_editor):
    """
    Verschlüsselt bestehende Klartext-Daten in Client-Modell.
    
    Diese Funktion wird nach dem Ändern der Feldtypen ausgeführt,
    um bestehende Klartext-Daten zu verschlüsseln.
    """
    import adeacore.encryption
    Client = apps.get_model('adeacore', 'Client')
    encryption_manager = adeacore.encryption.get_encryption_manager()
    
    # Felder die verschlüsselt werden müssen
    encrypted_fields = [
        'email', 'phone', 'street', 'house_number', 'zipcode', 'city',
        'mwst_nr', 'rechnungs_email', 'steuerkanton'
    ]
    
    # Date-Feld separat behandeln
    date_field = 'geburtsdatum'
    
    updated_count = 0
    for client in Client.objects.all():
        needs_update = False
        
        # Verschlüssele String-Felder
        for field_name in encrypted_fields:
            value = getattr(client, field_name, None)
            if value and not value.startswith('gAAAAAB'):  # Nicht bereits verschlüsselt (Fernet-Präfix)
                try:
                    encrypted = encryption_manager.encrypt(str(value))
                    setattr(client, field_name, encrypted)
                    needs_update = True
                except Exception as e:
                    # Falls Verschlüsselung fehlschlägt, überspringe Feld
                    import logging
                    logger = logging.getLogger(__name__)
                    logger.warning(f"Verschlüsselung fehlgeschlagen für Client {client.pk}, Feld {field_name}: {e}")
        
        # Verschlüssele Date-Feld
        if hasattr(client, date_field):
            value = getattr(client, date_field, None)
            if value:
                # Prüfe ob bereits verschlüsselt (als String gespeichert)
                if isinstance(value, str) and not value.startswith('gAAAAAB'):
                    try:
                        from django.utils.dateparse import parse_date
                        date_obj = parse_date(value)
                        if date_obj:
                            encrypted = encryption_manager.encrypt(date_obj.isoformat())
                            setattr(client, date_field, encrypted)
                            needs_update = True
                    except Exception:
                        pass
        
        if needs_update:
            # Speichere ohne save() zu rufen (vermeidet Audit-Log bei Migration)
            Client.objects.filter(pk=client.pk).update(**{
                field: getattr(client, field) for field in encrypted_fields + [date_field]
                if hasattr(client, field)
            })
            updated_count += 1
    
    if updated_count > 0:
        import logging
        logger = logging.getLogger(__name__)
        logger.info(f"Verschlüsselt {updated_count} Client-Objekte")


def reverse_encryption(apps, schema_editor):
    """
    Entschlüsselt Daten zurück zu Klartext (für Rollback).
    
    WARNUNG: Diese Funktion sollte nur für Tests verwendet werden!
    """
    import adeacore.encryption
    Client = apps.get_model('adeacore', 'Client')
    encryption_manager = adeacore.encryption.get_encryption_manager()
    
    encrypted_fields = [
        'email', 'phone', 'street', 'house_number', 'zipcode', 'city',
        'mwst_nr', 'rechnungs_email', 'steuerkanton', 'geburtsdatum'
    ]
    
    for client in Client.objects.all():
        needs_update = False
        update_data = {}
        
        for field_name in encrypted_fields:
            value = getattr(client, field_name, None)
            if value and value.startswith('gAAAAAB'):  # Verschlüsselt
                try:
                    decrypted = encryption_manager.decrypt(value)
                    update_data[field_name] = decrypted
                    needs_update = True
                except Exception:
                    pass
        
        if needs_update:
            Client.objects.filter(pk=client.pk).update(**update_data)


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0017_add_sachbearbeiter_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=adeacore.fields.EncryptedEmailField(blank=True, max_length=255, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='geburtsdatum',
            field=adeacore.fields.EncryptedDateField(blank=True, help_text='Geburtsdatum (nur PRIVAT)', null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='client',
            name='house_number',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=50, verbose_name='Hausnummer'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mwst_nr',
            field=adeacore.fields.EncryptedCharField(blank=True, help_text='MWST-Nummer / UID (in CH identisch, nur FIRMA)', max_length=50, verbose_name='MWST-Nummer / UID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rechnungs_email',
            field=adeacore.fields.EncryptedEmailField(blank=True, help_text='E-Mail-Adresse für Rechnungen (nur FIRMA)', max_length=255, null=True, verbose_name='Rechnungs-E-Mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='steuerkanton',
            field=adeacore.fields.EncryptedCharField(blank=True, help_text='Steuerkanton (nur PRIVAT)', max_length=50, verbose_name='Steuerkanton'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Strasse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=20, verbose_name='PLZ'),
        ),
        # Datenmigration: Verschlüssele bestehende Daten
        migrations.RunPython(encrypt_existing_data, reverse_encryption),
    ]
