# Generated by Django 5.1.2 on 2025-11-26 13:40

import adeacore.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0017_add_sachbearbeiter_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=adeacore.fields.EncryptedEmailField(blank=True, max_length=255, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='geburtsdatum',
            field=adeacore.fields.EncryptedDateField(blank=True, help_text='Geburtsdatum (nur PRIVAT)', null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='client',
            name='house_number',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=50, verbose_name='Hausnummer'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mwst_nr',
            field=adeacore.fields.EncryptedCharField(blank=True, help_text='MWST-Nummer / UID (in CH identisch, nur FIRMA)', max_length=50, verbose_name='MWST-Nummer / UID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rechnungs_email',
            field=adeacore.fields.EncryptedEmailField(blank=True, help_text='E-Mail-Adresse für Rechnungen (nur FIRMA)', max_length=255, null=True, verbose_name='Rechnungs-E-Mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='steuerkanton',
            field=adeacore.fields.EncryptedCharField(blank=True, help_text='Steuerkanton (nur PRIVAT)', max_length=50, verbose_name='Steuerkanton'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Strasse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=20, verbose_name='PLZ'),
        ),
    ]
