# Generated by Django 5.1.2 on 2025-11-26 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0018_encrypt_client_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('AKTIV', 'Aktiv'), ('INAKTIV', 'Inaktiv'), ('POTENZIELL', 'Potenziell'), ('GESPERRT', 'Gesperrt')], default='AKTIV', help_text='Status des Mandanten', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='client',
            name='status_geaendert_am',
            field=models.DateTimeField(blank=True, help_text='Datum der letzten Status-Änderung', null=True, verbose_name='Status geändert am'),
        ),
        migrations.AddField(
            model_name='client',
            name='status_grund',
            field=models.TextField(blank=True, help_text='Grund für Inaktivität oder Sperrung (optional)', verbose_name='Grund für Status'),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('EMAIL', 'E-Mail'), ('ANRUF', 'Anruf'), ('MEETING', 'Meeting'), ('NOTIZ', 'Notiz'), ('SONSTIGES', 'Sonstiges')], default='NOTIZ', max_length=20, verbose_name='Typ')),
                ('subject', models.CharField(blank=True, help_text='Betreff (E-Mail) oder Thema (Anruf/Meeting)', max_length=255, verbose_name='Betreff/Thema')),
                ('content', models.TextField(help_text='Inhalt der Kommunikation', verbose_name='Inhalt')),
                ('date', models.DateTimeField(help_text='Datum und Uhrzeit der Kommunikation', verbose_name='Datum')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Dauer bei Anrufen/Meetings (optional)', null=True, verbose_name='Dauer (Minuten)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='adeacore.client', verbose_name='Mandant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Kommunikation',
                'verbose_name_plural': 'Kommunikationen',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('VERTRAG', 'Vertrag'), ('STEUER', 'Steuer'), ('RECHNUNG', 'Rechnung'), ('BELEG', 'Beleg'), ('SONSTIGES', 'Sonstiges')], default='SONSTIGES', max_length=20, verbose_name='Typ')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('file', models.FileField(help_text='Hochgeladene Datei', upload_to='documents/%Y/%m/', verbose_name='Datei')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Größe der Datei in Bytes', null=True, verbose_name='Dateigröße (Bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='adeacore.client', verbose_name='Mandant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('MEETING', 'Meeting'), ('FRIST', 'Frist'), ('ERINNERUNG', 'Erinnerung'), ('TERMIN', 'Termin'), ('SONSTIGES', 'Sonstiges')], default='TERMIN', max_length=20, verbose_name='Typ')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('start_date', models.DateTimeField(help_text='Startdatum und -zeit', verbose_name='Startdatum')),
                ('end_date', models.DateTimeField(blank=True, help_text='Enddatum und -zeit (optional)', null=True, verbose_name='Enddatum')),
                ('reminder_date', models.DateTimeField(blank=True, help_text='Erinnerung vor dem Termin (optional)', null=True, verbose_name='Erinnerung')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Erinnerung gesendet')),
                ('is_recurring', models.BooleanField(default=False, help_text='Wiederkehrender Termin (z.B. monatlich)', verbose_name='Wiederkehrend')),
                ('recurring_pattern', models.CharField(blank=True, help_text="z.B. 'MONATLICH', 'JAERLICH'", max_length=50, verbose_name='Wiederholungsmuster')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='adeacore.client', verbose_name='Mandant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termine',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Eindeutige Rechnungsnummer', max_length=100, unique=True, verbose_name='Rechnungsnummer')),
                ('invoice_date', models.DateField(verbose_name='Rechnungsdatum')),
                ('due_date', models.DateField(help_text='Fälligkeitsdatum basierend auf Zahlungsziel', verbose_name='Fälligkeitsdatum')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Rechnungsbetrag in CHF', max_digits=10, verbose_name='Betrag')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Bereits bezahlter Betrag', max_digits=10, verbose_name='Bezahlter Betrag')),
                ('payment_status', models.CharField(choices=[('OFFEN', 'Offen'), ('TEILWEISE', 'Teilweise bezahlt'), ('BEZAHLT', 'Bezahlt'), ('UEBERFAELLIG', 'Überfällig'), ('STORNIERT', 'Storniert')], default='OFFEN', max_length=20, verbose_name='Zahlungsstatus')),
                ('payment_date', models.DateField(blank=True, help_text='Datum der Zahlung', null=True, verbose_name='Zahlungsdatum')),
                ('description', models.TextField(blank=True, help_text='Beschreibung der Leistungen', verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='adeacore.client', verbose_name='Mandant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
    ]
