# Generated by Django 5.1.2 on 2025-12-02 08:45

import adeacore.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0019_add_crm_features'),
    ]

    operations = [
        # Erhöhe max_length für verschlüsselte Felder, da verschlüsselte Werte sehr lang sein können
        migrations.AlterField(
            model_name='client',
            name='email',
            field=adeacore.fields.EncryptedEmailField(blank=True, max_length=1000, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=1000, verbose_name='Strasse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='house_number',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='Hausnummer'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=1000, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mwst_nr',
            field=adeacore.fields.EncryptedCharField(blank=True, help_text='MWST-Nummer / UID (in CH identisch, nur FIRMA)', max_length=500, verbose_name='MWST-Nummer / UID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rechnungs_email',
            field=adeacore.fields.EncryptedEmailField(blank=True, help_text='E-Mail-Adresse für Rechnungen (nur FIRMA)', max_length=1000, null=True, verbose_name='Rechnungs-E-Mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='steuerkanton',
            field=adeacore.fields.EncryptedCharField(blank=True, help_text='Steuerkanton (nur PRIVAT)', max_length=500, verbose_name='Steuerkanton'),
        ),
    ]
