# Generated by Django 5.1.2 on 2025-12-29 15:37

import adeacore.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0020_increase_encrypted_field_lengths'),
        ('adeazeit', '0024_timeentry_verrechnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Adea Treuhand', help_text='Vollständiger Firmenname', max_length=255, verbose_name='Firmenname')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Strasse')),
                ('house_number', models.CharField(blank=True, max_length=50, verbose_name='Hausnummer')),
                ('zipcode', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Ort')),
                ('country', models.CharField(default='Schweiz', max_length=100, verbose_name='Land')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('mwst_nr', adeacore.fields.EncryptedCharField(blank=True, help_text='Format: CHE-123.456.789 MWST', max_length=500, verbose_name='MWST-Nummer (UID MWST)')),
                ('iban', adeacore.fields.EncryptedCharField(blank=True, help_text='IBAN für QR-Rechnung', max_length=100, verbose_name='IBAN')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Bank')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firmendaten',
                'verbose_name_plural': 'Firmendaten',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Leistungsbeschreibung (aus Kommentar)', verbose_name='Beschreibung')),
                ('service_type_code', models.CharField(help_text='Service-Typ Code (z.B. STEU, BUCH)', max_length=50, verbose_name='Service-Typ')),
                ('employee_name', models.CharField(help_text='Name der Mitarbeiterin', max_length=255, verbose_name='Mitarbeiterin')),
                ('service_date', models.DateField(help_text='Datum der Leistungserbringung', verbose_name='Leistungsdatum')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Anzahl Stunden', max_digits=5, verbose_name='Anzahl (Stunden)')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Stundensatz in CHF', max_digits=10, verbose_name='Einzelpreis (Stundensatz)')),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Nettobetrag (ohne MWST)', max_digits=10, verbose_name='Nettobetrag')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, help_text='MWST-Satz (z.B. 7.7)', max_digits=5, verbose_name='MWST-Satz (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, help_text='MWST-Betrag', max_digits=10, verbose_name='MWST-Betrag')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Bruttobetrag (mit MWST)', max_digits=10, verbose_name='Bruttobetrag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adeacore.invoice', verbose_name='Rechnung')),
                ('time_entry', models.ForeignKey(blank=True, help_text='Verknüpfung zum ursprünglichen Zeiteintrag', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='adeazeit.timeentry', verbose_name='Zeiteintrag')),
            ],
            options={
                'verbose_name': 'Rechnungsposition',
                'verbose_name_plural': 'Rechnungspositionen',
                'ordering': ['service_date', 'id'],
            },
        ),
    ]
