# Generated by Django 5.1.2 on 2025-12-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0021_add_company_data_and_invoice_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nettobetrag ohne MWST', max_digits=10, verbose_name='Nettobetrag'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='MWST-Betrag', max_digits=10, verbose_name='MWST-Betrag'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=7.7, help_text='MWST-Satz (z.B. 7.7)', max_digits=5, verbose_name='MWST-Satz (%)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Rechnungsbetrag in CHF (Bruttobetrag)', max_digits=10, verbose_name='Betrag'),
        ),
    ]
