# Generated by Django 5.1.2 on 2026-01-07 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0022_add_invoice_vat_fields'),
        ('adeazeit', '0025_task_archiviert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titel der Notiz (z.B. 'Steuererklärung 2026')", max_length=255, verbose_name='Titel')),
                ('content', models.TextField(help_text='Inhalt der Notiz', verbose_name='Inhalt')),
                ('note_type', models.CharField(choices=[('STEUER', 'Steuererklärung'), ('QUARTAL', 'Quartalsweise'), ('MONAT', 'Monatlich'), ('ALLGEMEIN', 'Allgemein'), ('ERINNERUNG', 'Erinnerung')], default='ALLGEMEIN', help_text='Typ der Notiz', max_length=20, verbose_name='Typ')),
                ('note_date', models.DateField(help_text='Datum der Notiz (z.B. Datum der Steuererklärung oder Quartal/Monat)', verbose_name='Datum')),
                ('status', models.CharField(choices=[('OFFEN', 'Offen'), ('ERLEDIGT', 'Erledigt')], default='OFFEN', max_length=20, verbose_name='Status')),
                ('archiviert', models.BooleanField(default=False, help_text='Erledigte Notizen können archiviert werden', verbose_name='Archiviert')),
                ('erledigt_am', models.DateTimeField(blank=True, help_text='Datum und Uhrzeit, wann die Notiz als erledigt markiert wurde', null=True, verbose_name='Erledigt am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='adeacore.client', verbose_name='Mandant')),
                ('created_by', models.ForeignKey(blank=True, help_text='Benutzer, der die Notiz erstellt hat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_notes', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('task', models.ForeignKey(blank=True, help_text='Optional: Verknüpfung zu einer Aufgabe in AdeaZeit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_notes', to='adeazeit.task', verbose_name='Verknüpfte Aufgabe')),
            ],
            options={
                'verbose_name': 'Mandanten-Notiz',
                'verbose_name_plural': 'Mandanten-Notizen',
                'ordering': ['-note_date', '-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='adeacore_cnote_client_st_idx'), models.Index(fields=['client', 'archiviert'], name='adeacore_cnote_client_ar_idx'), models.Index(fields=['note_date'], name='adeacore_cnote_date_idx')],
            },
        ),
    ]
