# Generated by GPT on 2026-01-15

import adeacore.fields
from django.db import migrations


class Migration(migrations.Migration):
    """
    Fix: `EncryptedDateField` stores encrypted dates as strings.

    Older DB states may have created `geburtsdatum` as a DATE column (because the field
    previously inherited from DateField). That breaks encrypted values (SQLite converters
    yield NULL / Postgres would reject non-date values).

    This migration forces the column to a text-like type by altering the field definition.
    """

    dependencies = [
        ("adeacore", "0023_clientnote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="geburtsdatum",
            field=adeacore.fields.EncryptedDateField(
                blank=True,
                null=True,
                max_length=1000,
                help_text="Geburtsdatum (nur PRIVAT)",
                verbose_name="Geburtsdatum",
            ),
        ),
    ]

