# Generated by Django 5.2.10 on 2026-02-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0024_alter_client_geburtsdatum_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='qst_prozent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='QST-Prozentsatz für diesen Monat (z.B. 5.00 für 5%). Kann monatlich variieren bei Stundenlöhnen.', max_digits=5, null=True),
        ),
    ]
