# Generated by Django 5.2.10 on 2026-02-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0025_add_qst_prozent_to_payrollrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vacation_weeks',
            field=models.IntegerField(choices=[(4, '4 Wochen'), (5, '5 Wochen'), (6, '6 Wochen')], default=5, help_text='Anzahl Ferienwochen (für Ferienentschädigung bei Stundenlöhnen)'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='fak_employer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='FAK-Beitrag Arbeitgeber (1.025% vom Bruttolohn)', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='vk_employer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Verwaltungskosten Arbeitgeber (5.0% vom Total AHV-Beitrag)', max_digits=10),
        ),
    ]
