# Generated by Django 5.2.10 on 2026-02-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0026_add_uvg_parameter_fak_vk_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='work_canton',
            field=models.CharField(blank=True, help_text="Kanton des Arbeitgebersitzes (für FAK und andere kantonale Beiträge). Z.B. 'AG', 'ZH', 'BE'", max_length=50, null=True, verbose_name='Arbeitskanton'),
        ),
    ]
