# Generated by Django 5.2.10 on 2026-02-02 17:33

import adeacore.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0027_add_fak_parameter_canton_work_canton'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ahv_nummer',
            field=adeacore.fields.EncryptedCharField(blank=True, help_text='AHV-Nummer im Format 756.XXXX.XXXX.XX', max_length=50, verbose_name='AHV-Nummer'),
        ),
        migrations.AddField(
            model_name='employee',
            name='austrittsdatum',
            field=models.DateField(blank=True, help_text='Datum des Austritts aus der Firma', null=True, verbose_name='Austrittsdatum'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=1000, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=adeacore.fields.EncryptedCharField(blank=True, default='CH', help_text='ISO-Code (CH, DE, FR, AT) für Grenzgänger', max_length=500, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='employee',
            name='eintrittsdatum',
            field=models.DateField(blank=True, help_text='Datum des Eintritts in die Firma', null=True, verbose_name='Eintrittsdatum'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=adeacore.fields.EncryptedEmailField(blank=True, max_length=1000, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='employee',
            name='geburtsdatum',
            field=adeacore.fields.EncryptedDateField(blank=True, help_text='Geburtsdatum des Mitarbeiters', max_length=1000, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='Mobiltelefon'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personalnummer',
            field=models.CharField(blank=True, help_text='Eindeutige Personalnummer des Mitarbeiters', max_length=50, verbose_name='Personal-Nr.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='employee',
            name='street',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=1000, verbose_name='Strasse'),
        ),
        migrations.AddField(
            model_name='employee',
            name='taetigkeit_branche',
            field=models.CharField(blank=True, help_text="z.B. 'Coiffeur', 'Gastro'", max_length=255, verbose_name='Tätigkeit/Branche'),
        ),
        migrations.AddField(
            model_name='employee',
            name='zipcode',
            field=adeacore.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='zivilstand',
            field=models.CharField(choices=[('LEDIG', 'Ledig'), ('VERHEIRATET', 'Verheiratet'), ('GESCHIEDEN', 'Geschieden'), ('VERWITWET', 'Verwitwet'), ('KONKUBINAT', 'Konkubinat'), ('UNBEKANNT', 'Unbekannt')], default='UNBEKANNT', help_text='Zivilstand des Mitarbeiters', max_length=20, verbose_name='Zivilstand'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Stundensatz (CHF)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rolle/Tätigkeit'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='fak_employer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='FAK-Beitrag Arbeitgeber (1.0% vom Bruttolohn, gemäss Excel-Vorlage)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='vk_employer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Verwaltungskosten Arbeitgeber (3.0% vom Total AHV-Beitrag, gemäss Excel-Vorlage)', max_digits=10),
        ),
    ]
