# Generated by Django 5.2.10 on 2026-02-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0028_add_employee_excel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monatlicher Bruttolohn für Monatslöhne. Wenn 0, wird Stundenlohn verwendet.', max_digits=10, verbose_name='Monatslohn (CHF)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stundensatz für Stundenlöhne. Wenn 0, wird Monatslohn verwendet.', max_digits=6, verbose_name='Stundensatz (CHF)'),
        ),
    ]
