# Generated by Django 5.1.2 on 2026-02-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0029_add_employee_monthly_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='manual_bvg_employee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manueller BVG-Arbeitnehmerbeitrag (falls nicht automatisch berechnet). Wird zu berechneten Beiträgen addiert.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='manual_bvg_employer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manueller BVG-Arbeitgeberbeitrag (falls nicht automatisch berechnet). Wird zu berechneten Beiträgen addiert.', max_digits=12),
        ),
    ]
