# Generated by Django 5.1.2 on 2026-02-03 14:10

import adeacore.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0030_add_manual_bvg_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='iban',
            field=adeacore.fields.EncryptedCharField(blank=True, help_text='IBAN für Lohnauszahlung', max_length=100, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pensum',
            field=models.DecimalField(decimal_places=1, default=100, help_text='Arbeitspensum in Prozent (z.B. 80 für 80%, 100 für 100%)', max_digits=5, verbose_name='Arbeitspensum (%)'),
        ),
    ]
