# Generated by Django 5.2.17 on 2026-09-28 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adeacore", "0041_invoiceitem_manual_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("AKONTO", "Akonto")],
                default="NORMAL",
                help_text="Akontorechnung oder normale Rechnung (inkl. Schlussrechnung).",
                max_length=10,
                verbose_name="Rechnungstyp",
            ),
        ),
        migrations.CreateModel(
            name="AkontoPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fixbetrag pro Periode, netto vor MWST.",
                        max_digits=10,
                        verbose_name="Akonto-Betrag (CHF)",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("MONATLICH", "Monatlich"),
                            ("QUARTALSWEISE", "Quartalsweise"),
                            ("JAEHRLICH", "Jährlich"),
                        ],
                        default="QUARTALSWEISE",
                        max_length=20,
                        verbose_name="Intervall",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional: Enddatum des Plans.",
                        null=True,
                        verbose_name="Ende",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="akonto_plans",
                        to="adeacore.client",
                        verbose_name="Mandant",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="akonto_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Akonto-Plan",
                "verbose_name_plural": "Akonto-Pläne",
                "ordering": ["client__name", "-active", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="akonto_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Nur gesetzt bei Akontorechnungen: der zugrunde liegende Akonto-Plan.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="adeacore.akontoplan",
                verbose_name="Akonto-Plan",
            ),
        ),
    ]
