# Generated by Django 5.1.2 on 2025-11-20 14:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adeacore', '0016_remove_uid_field_use_mwst_nr'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('rolle', models.CharField(blank=True, max_length=255, verbose_name='Rolle')),
                ('stundensatz', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Stundensatz')),
                ('sollstunden_woche', models.DecimalField(decimal_places=2, default=Decimal('42.00'), max_digits=5, verbose_name='Sollstunden/Woche')),
                ('ferien_pro_jahr', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5, verbose_name='Ferien pro Jahr')),
                ('eintrittsdatum', models.DateField(verbose_name='Eintrittsdatum')),
                ('austrittsdatum', models.DateField(blank=True, null=True, verbose_name='Austrittsdatum')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interne Mitarbeiterin',
                'verbose_name_plural': 'Interne Mitarbeitende',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('standard_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Standard-Stundensatz')),
                ('billable', models.BooleanField(default=True, verbose_name='Verrechenbar')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service-Typ',
                'verbose_name_plural': 'Service-Typen',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ZeitProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Projektname')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeit_projects', to='adeacore.client', verbose_name='Mandant')),
            ],
            options={
                'verbose_name': 'Zeit-Projekt',
                'verbose_name_plural': 'Zeit-Projekte',
                'ordering': ['client', 'name'],
                'unique_together': {('client', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('FERIEN', 'Ferien'), ('KRANK', 'Krankheit'), ('FEIERTAG', 'Feiertag'), ('UNBEZAHLT', 'Unbezahlter Urlaub')], max_length=20, verbose_name='Typ')),
                ('datum_von', models.DateField(verbose_name='Von')),
                ('datum_bis', models.DateField(verbose_name='Bis')),
                ('kommentar', models.TextField(blank=True, verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='adeazeit.employeeinternal', verbose_name='Mitarbeiterin')),
            ],
            options={
                'verbose_name': 'Abwesenheit',
                'verbose_name_plural': 'Abwesenheiten',
                'ordering': ['-datum_von'],
                'indexes': [models.Index(fields=['mitarbeiter', 'datum_von'], name='adeazeit_ab_mitarbe_ada11c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('start', models.TimeField(blank=True, null=True, verbose_name='Startzeit')),
                ('ende', models.TimeField(blank=True, null=True, verbose_name='Endzeit')),
                ('dauer', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Dauer (Stunden)')),
                ('kommentar', models.TextField(blank=True, verbose_name='Kommentar')),
                ('billable', models.BooleanField(default=True, verbose_name='Verrechenbar')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stundensatz')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='adeacore.client', verbose_name='Mandant')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='adeazeit.employeeinternal', verbose_name='Mitarbeiterin')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='adeazeit.servicetype', verbose_name='Service-Typ')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='adeazeit.zeitproject', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Zeiteintrag',
                'verbose_name_plural': 'Zeiteinträge',
                'ordering': ['-datum', '-start'],
                'indexes': [models.Index(fields=['datum', 'mitarbeiter'], name='adeazeit_ti_datum_e9a03f_idx'), models.Index(fields=['client', 'datum'], name='adeazeit_ti_client__200d12_idx')],
            },
        ),
    ]
