# Generated by Django 5.1.2 on 2025-11-20 14:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeazeit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinternal',
            name='employment_end',
            field=models.DateField(blank=True, null=True, verbose_name='Beschäftigungsende'),
        ),
        migrations.AddField(
            model_name='employeeinternal',
            name='employment_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Beispiel: 100.00, 60.00', max_digits=5, verbose_name='Beschäftigungsgrad (%)'),
        ),
        migrations.AddField(
            model_name='employeeinternal',
            name='employment_start',
            field=models.DateField(blank=True, null=True, verbose_name='Beschäftigungsbeginn'),
        ),
        migrations.AddField(
            model_name='employeeinternal',
            name='function_title',
            field=models.CharField(default='', max_length=255, verbose_name='Funktion'),
        ),
        migrations.AddField(
            model_name='employeeinternal',
            name='holiday_model',
            field=models.CharField(blank=True, help_text='Freitext', max_length=255, null=True, verbose_name='Feiertagsmodell'),
        ),
        migrations.AddField(
            model_name='employeeinternal',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notizen'),
        ),
        migrations.AddField(
            model_name='employeeinternal',
            name='vacation_days_per_year',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='z.B. 20.00 / 25.00', max_digits=5, null=True, verbose_name='Ferientage pro Jahr'),
        ),
        migrations.AddField(
            model_name='employeeinternal',
            name='weekly_soll_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('42.00'), help_text='Gesamte wöchentliche Sollstunden (z.B. 42.00 oder 40.00)', max_digits=5, verbose_name='Wöchentliche Sollstunden'),
        ),
        migrations.AddField(
            model_name='employeeinternal',
            name='weekly_working_days',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='z.B. 5.0 / 4.5 / 4.0', max_digits=4, null=True, verbose_name='Wöchentliche Arbeitstage'),
        ),
        migrations.AddField(
            model_name='employeeinternal',
            name='work_canton',
            field=models.CharField(blank=True, help_text='Für zukünftige Feiertagsmodelle', max_length=50, null=True, verbose_name='Arbeitskanton'),
        ),
        migrations.AlterField(
            model_name='employeeinternal',
            name='ferien_pro_jahr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Veraltet - verwende vacation_days_per_year', max_digits=5, null=True, verbose_name='Ferien pro Jahr (Legacy)'),
        ),
        migrations.AlterField(
            model_name='employeeinternal',
            name='sollstunden_woche',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Veraltet - verwende weekly_soll_hours', max_digits=5, null=True, verbose_name='Sollstunden/Woche (Legacy)'),
        ),
    ]
