# Generated by Django 5.1.2 on 2025-11-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeazeit', '0004_extend_absence_add_holiday'),
    ]

    operations = [
        # Index wird direkt erstellt, da er möglicherweise nicht existiert
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS adeazeit_ab_employe_c4ea6a_idx ON adeazeit_absence(employee_id, date_from);",
            reverse_sql="DROP INDEX IF EXISTS adeazeit_ab_employe_c4ea6a_idx;",
        ),
        migrations.AlterField(
            model_name='absence',
            name='absence_type',
            field=models.CharField(choices=[('FERIEN', 'Ferien'), ('KRANK', 'Krankheit'), ('UNFALL', 'Unfall'), ('FEIERTAG', 'Feiertag'), ('UNBEZAHLT', 'Unbezahlter Urlaub'), ('WEITERBILDUNG', 'Weiterbildung'), ('SONSTIGES', 'Sonstiges')], max_length=20, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='date_from',
            field=models.DateField(verbose_name='Von Datum'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='date_to',
            field=models.DateField(verbose_name='Bis Datum'),
        ),
    ]
