# Generated by Django 5.1.2 on 2025-11-21 08:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeazeit', '0005_remove_absence_adeazeit_ab_mitarbe_ada11c_idx_and_more'),
    ]

    operations = [
        # RemoveIndex entfernt, da Index bereits in 0003 entfernt wurde
        # migrations.RemoveIndex(
        #     model_name='absence',
        #     name='adeazeit_ab_mitarbe_ada11c_idx',
        # ),
        # RenameIndex entfernt, da Index bereits in 0005 erstellt wurde
        # migrations.RenameIndex(
        #     model_name='absence',
        #     new_name='adeazeit_ab_employe_c4ea6a_idx',
        #     old_name='adeazeit_abs_employe_123456_idx',
        # ),
        migrations.AlterField(
            model_name='employeeinternal',
            name='code',
            field=models.CharField(help_text='Eindeutiger Kurzcode für den Mitarbeiter (z.B. MM, EMP001, AM)', max_length=20, unique=True, verbose_name='Mitarbeiterkürzel'),
        ),
        migrations.AlterField(
            model_name='employeeinternal',
            name='eintrittsdatum',
            field=models.DateField(blank=True, null=True, verbose_name='Eintrittsdatum'),
        ),
        migrations.AlterField(
            model_name='employeeinternal',
            name='stundensatz',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Koeffizient für die Verrechnung von Services (z.B. 1.3 = 30% Aufschlag auf Standard-Stundensatz)', max_digits=10, verbose_name='Koeffizient'),
        ),
    ]
