# Generated by Django 5.1.2 on 2025-11-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeazeit', '0006_remove_absence_adeazeit_ab_mitarbe_ada11c_idx_and_more'),
    ]

    operations = [
        # RemoveIndex und RenameIndex entfernt, da bereits in vorherigen Migrationen behandelt
        migrations.AlterField(
            model_name='employeeinternal',
            name='code',
            field=models.CharField(help_text='Eindeutiger Kurzcode für den Mitarbeiter (z.B. MM, EMP001, AM)', max_length=20, unique=True, verbose_name='Mitarbeiterkürzel'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wird automatisch aus Service-Typ übernommen, falls nicht gesetzt', max_digits=10, null=True, verbose_name='Stundensatz'),
        ),
    ]
