# Generated by Django 5.1.2 on 2025-11-21 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0016_remove_uid_field_use_mwst_nr'),
        ('adeazeit', '0007_remove_absence_adeazeit_ab_mitarbe_ada11c_idx_and_more'),
    ]

    operations = [
        # RemoveIndex und RenameIndex entfernt, da bereits in vorherigen Migrationen behandelt
        # Migration wurde bereits gefaked, da die Datenbank bereits das richtige Schema hat
        migrations.AlterField(
            model_name='timeentry',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Optional: Für interne Arbeiten leer lassen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='adeacore.client', verbose_name='Mandant'),
        ),
    ]
