# Generated by Django 5.1.2 on 2025-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeazeit', '0009_create_holiday_table'),
    ]

    operations = [
        # RemoveIndex entfernt, da Index nicht existiert
        migrations.AlterField(
            model_name='employeeinternal',
            name='code',
            field=models.CharField(help_text='Eindeutiger Kurzcode für den Mitarbeiter (z.B. MM, EMP001, AM)', max_length=20, unique=True, verbose_name='Mitarbeiterkürzel'),
        ),
    ]
