# Generated by Django 5.1.2 on 2025-11-21 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeazeit', '0010_remove_absence_adeazeit_ab_mitarbe_ada11c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Benutzerprofil',
                'verbose_name_plural': 'Benutzerprofile',
                'ordering': ['user__username'],
            },
        ),
        # RemoveIndex entfernt - Index existiert nicht mehr
        # migrations.RemoveIndex(
        #     model_name='absence',
        #     name='adeazeit_ab_mitarbe_ada11c_idx',
        # ),
        # RenameIndex entfernt - Index existiert möglicherweise nicht
        # migrations.RenameIndex(
        #     model_name='absence',
        #     new_name='adeazeit_ab_employe_c4ea6a_idx',
        #     old_name='adeazeit_abs_employe_123456_idx',
        # ),
        migrations.AlterField(
            model_name='employeeinternal',
            name='code',
            field=models.CharField(help_text='Eindeutiger Kurzcode für den Mitarbeiter (z.B. MM, EMP001)', max_length=20, unique=True, verbose_name='Mitarbeiterkürzel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Verknüpfung zum EmployeeInternal für Zeiterfassung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='adeazeit.employeeinternal', verbose_name='Mitarbeiterin'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adeazeit_profile', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
    ]
