# Generated by Django 5.1.2 on 2025-11-26 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0016_remove_uid_field_use_mwst_nr'),
        ('adeazeit', '0011_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(help_text="Kurze Beschreibung der Aufgabe (z.B. 'Steuererklärung Müller AG')", max_length=255, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, help_text='Detaillierte Beschreibung (optional)', verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('OFFEN', 'Offen'), ('IN_ARBEIT', 'In Arbeit'), ('ERLEDIGT', 'Erledigt')], default='OFFEN', max_length=20, verbose_name='Status')),
                ('prioritaet', models.CharField(choices=[('NIEDRIG', 'Niedrig'), ('MITTEL', 'Mittel'), ('HOCH', 'Hoch')], default='MITTEL', max_length=20, verbose_name='Priorität')),
                ('fälligkeitsdatum', models.DateField(blank=True, help_text='Wichtig für Treuhand: Steuerfristen, MwSt-Abgaben, etc.', null=True, verbose_name='Fälligkeitsdatum')),
                ('notizen', models.TextField(blank=True, help_text="Notizen zum aktuellen Stand (z.B. 'Warte auf Belege vom Kunden')", verbose_name='Notizen')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('erledigt_am', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
                'ordering': ['prioritaet', 'fälligkeitsdatum', '-erstellt_am'],
            },
        ),
        # Index wurde bereits in früheren Migrationen entfernt, daher mit RunSQL umhüllen
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS adeazeit_ab_mitarbe_ada11c_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # RenameIndex entfernt - Index wurde bereits in früheren Migrationen umbenannt oder existiert nicht
        # SQLite unterstützt kein ALTER INDEX RENAME, daher ignorieren wir diese Operation
        migrations.AddField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, help_text="Optional: Mandant zuordnen (z.B. 'Steuererklärung Müller AG')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='adeacore.client', verbose_name='Mandant'),
        ),
        migrations.AddField(
            model_name='task',
            name='mitarbeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='adeazeit.employeeinternal', verbose_name='Mitarbeiterin'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['mitarbeiter', 'status'], name='adeazeit_ta_mitarbe_492268_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['client', 'status'], name='adeazeit_ta_client__018f96_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['fälligkeitsdatum'], name='adeazeit_ta_fälligk_0cb4c5_idx'),
        ),
    ]
