# Generated by Django 5.1.2 on 2025-12-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adeazeit', '0015_remove_absence_adeazeit_ab_mitarbe_ada11c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='absence',
            name='adeazeit_ab_mitarbe_ada11c_idx',
        ),
        migrations.RenameIndex(
            model_name='absence',
            new_name='adeazeit_ab_employe_c4ea6a_idx',
            old_name='adeazeit_abs_employe_123456_idx',
        ),
    ]
