# Generated by Django 5.1.2 on 2025-12-02 11:32

from django.db import migrations

IDX_DROP = "adeazeit_ab_mitarbe_ada11c_idx"
IDX_OLD = "adeazeit_abs_employe_123456_idx"
IDX_NEW = "adeazeit_ab_employe_c4ea6a_idx"


def _try_rename_index(apps, schema_editor):
    """
    Versucht Index umzubenennen, falls er existiert.
    SQLite unterstützt kein ALTER INDEX RENAME, daher ignorieren wir das.
    """
    vendor = schema_editor.connection.vendor
    if vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute(f'ALTER INDEX "{IDX_OLD}" RENAME TO "{IDX_NEW}";')
        except Exception:
            # Index existiert evtl. nicht oder wurde schon umbenannt -> nicht blockieren
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('adeazeit', '0015_remove_absence_adeazeit_ab_mitarbe_ada11c_idx_and_more'),
    ]

    operations = [
        # Index wurde bereits in früheren Migrationen entfernt, daher nur DB-Operation ohne State-Änderung
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f'DROP INDEX IF EXISTS "{IDX_DROP}";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunPython(_try_rename_index, migrations.RunPython.noop),
            ],
            state_operations=[],
        ),
    ]
