# Generated by Django 5.1.2 on 2025-12-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0020_increase_encrypted_field_lengths'),
        ('adeazeit', '0020_remove_absence_adeazeit_ab_mitarbe_ada11c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('datum', models.DateField(auto_now_add=True, verbose_name='Datum')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Startzeit')),
            ],
            options={
                'verbose_name': 'Laufender Zeiteintrag',
                'verbose_name_plural': 'Laufende Zeiteinträge',
            },
        ),
        # Index wurde bereits in früheren Migrationen entfernt, daher nur DB-Operation ohne State-Änderung
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "adeazeit_ab_mitarbe_ada11c_idx";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[],
        ),
        migrations.AddField(
            model_name='runningtimeentry',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Nur bei externen Leistungen. Bei internen Leistungen leer lassen.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='running_timers', to='adeacore.client', verbose_name='Mandant'),
        ),
        migrations.AddField(
            model_name='runningtimeentry',
            name='mitarbeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_timer', to='adeazeit.employeeinternal', verbose_name='Mitarbeiterin'),
        ),
        migrations.AddField(
            model_name='runningtimeentry',
            name='projekt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='running_timers', to='adeazeit.zeitproject', verbose_name='Projekt'),
        ),
        migrations.AddField(
            model_name='runningtimeentry',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='running_timers', to='adeazeit.servicetype', verbose_name='Service-Typ'),
        ),
        migrations.AddConstraint(
            model_name='runningtimeentry',
            constraint=models.UniqueConstraint(fields=('mitarbeiter',), name='one_timer_per_employee'),
        ),
    ]
