# Generated by Django 5.1.2 on 2025-12-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adeazeit', '0021_add_running_time_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
