# Generated by Django 5.1.2 on 2025-12-05 13:48

import django.db.models.deletion
from django.db import migrations, models


def create_task_table_if_not_exists(apps, schema_editor):
    """Erstellt Task-Tabelle nur wenn sie nicht existiert."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Prüfe ob Tabelle existiert
        if db_alias == 'default':
            # PostgreSQL
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'adeazeit_task'
                );
            """)
        else:
            # SQLite
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='table' AND name='adeazeit_task';
            """)
        
        table_exists = cursor.fetchone()[0] if cursor.rowcount > 0 else False
        
        if not table_exists:
            # Erstelle Tabelle manuell
            Task = apps.get_model('adeazeit', 'Task')
            schema_editor.create_model(Task)


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0020_increase_encrypted_field_lengths'),
        ('adeazeit', '0021_add_running_time_entry'),  # Direkt nach 0021, überspringe 0022
    ]

    operations = [
        migrations.RunPython(
            create_task_table_if_not_exists,
            migrations.RunPython.noop,  # Reverse: nichts tun
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(help_text="Kurze Beschreibung der Aufgabe (z.B. 'Steuererklärung Müller AG')", max_length=255, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, help_text='Detaillierte Beschreibung (optional)', verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('OFFEN', 'Offen'), ('IN_ARBEIT', 'In Arbeit'), ('ERLEDIGT', 'Erledigt')], default='OFFEN', max_length=20, verbose_name='Status')),
                ('prioritaet', models.CharField(choices=[('NIEDRIG', 'Niedrig'), ('MITTEL', 'Mittel'), ('HOCH', 'Hoch')], default='MITTEL', max_length=20, verbose_name='Priorität')),
                ('fälligkeitsdatum', models.DateField(blank=True, help_text='Wichtig für Treuhand: Steuerfristen, MwSt-Abgaben, etc.', null=True, verbose_name='Fälligkeitsdatum')),
                ('notizen', models.TextField(blank=True, help_text="Notizen zum aktuellen Stand (z.B. 'Warte auf Belege vom Kunden')", verbose_name='Notizen')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('erledigt_am', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('client', models.ForeignKey(blank=True, help_text="Optional: Mandant zuordnen (z.B. 'Steuererklärung Müller AG')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='adeacore.client', verbose_name='Mandant')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='adeazeit.employeeinternal', verbose_name='Mitarbeiterin')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
                'ordering': ['prioritaet', 'fälligkeitsdatum', '-erstellt_am'],
                'indexes': [models.Index(fields=['mitarbeiter', 'status'], name='adeazeit_ta_mitarbe_492268_idx'), models.Index(fields=['client', 'status'], name='adeazeit_ta_client__018f96_idx'), models.Index(fields=['fälligkeitsdatum'], name='adeazeit_ta_fälligk_0cb4c5_idx')],
            },
        ),
    ]
