# Generated by Django 5.1.2 on 2025-12-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeazeit', '0023_restore_task_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='verrechnet',
            field=models.BooleanField(default=False, help_text='Zeit wurde bereits verrechnet/invoiced', verbose_name='Verrechnet'),
        ),
    ]
