# Generated by Django 5.1.2 on 2026-01-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeazeit', '0024_timeentry_verrechnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archiviert',
            field=models.BooleanField(default=False, help_text='Erledigte Aufgaben werden nach 7 Tagen automatisch archiviert', verbose_name='Archiviert'),
        ),
    ]
