# Generated by Django 5.1.2 on 2026-01-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adeacore', '0023_clientnote'),
        ('adeazeit', '0025_task_archiviert'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['mitarbeiter', 'datum', 'start', 'ende'], name='adeazeit_te_overlap_idx'),
        ),
    ]
