# Generated by Django 5.1.2 on 2026-01-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adeazeit', '0026_add_overlap_index'),
        ('adeazeit', '0027_repair_absence_index'),
    ]

    operations = [
    ]
