"""
Django settings for adeacore project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Lade .env Datei wenn vorhanden (für lokale Entwicklung)
# In Production sollten Environment-Variablen direkt gesetzt werden
try:
    from dotenv import load_dotenv
    env_path = BASE_DIR / '.env'
    if env_path.exists():
        load_dotenv(env_path)
except ImportError:
    # python-dotenv nicht installiert - kein Problem, Environment-Variablen werden direkt verwendet
    pass


# ============================================================================
# SECURITY SETTINGS - Environment-basiert
# ============================================================================

def get_env_variable(var_name, default=None):
    """
    Holt eine Environment-Variable oder wirft einen Fehler wenn nicht vorhanden.
    """
    try:
        return os.environ[var_name]
    except KeyError:
        if default is not None:
            return default
        error_msg = f"Setze die Environment-Variable {var_name}"
        raise ImproperlyConfigured(error_msg)


# SECRET_KEY - KRITISCH: Muss aus Environment-Variable kommen!
SECRET_KEY = get_env_variable(
    'DJANGO_SECRET_KEY',
    default='django-insecure-2sq0xh0_=kcvx63ib^=2_&2_zf+$*vjr+mfn62h@cxb2^$+qw!'
)

# DEBUG - In Production immer False!
DEBUG = get_env_variable('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

# ALLOWED_HOSTS - Liste der erlaubten Domains
ALLOWED_HOSTS_STR = get_env_variable('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'adeacore.apps.AdeacoreConfig',
    # AdeaTools Module
    'adeadesk',
    'adeazeit',
    'adealohn',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files für Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'adeacore.middleware.SessionSecurityMiddleware',  # Erweiterte Session-Sicherheit
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Security Headers (wenn nicht DEBUG)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 Jahr
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

ROOT_URLCONF = 'adeacore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'adeacore' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'adeacore.context_processors.current_client',
                'adeacore.context_processors.adeazeit_permissions',
                'adeacore.context_processors.adealohn_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'adeacore.wsgi.application'


# Cache Configuration (für Rate-Limiting)
# https://docs.djangoproject.com/en/5.1/topics/cache/

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'adeatools-cache',
        'TIMEOUT': 300,  # 5 Minuten Standard-Timeout
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# PostgreSQL für Production (Infomaniak Cloud), SQLite für Development
if 'DATABASE_URL' in os.environ:
    # PostgreSQL via DATABASE_URL (Infomaniak Cloud)
    try:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.parse(os.environ['DATABASE_URL'])
        }
    except ImportError:
        # Fallback zu manueller Konfiguration
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': get_env_variable('DB_NAME', 'adeatools'),
                'USER': get_env_variable('DB_USER', 'adeatools'),
                'PASSWORD': get_env_variable('DB_PASSWORD', ''),
                'HOST': get_env_variable('DB_HOST', 'localhost'),
                'PORT': get_env_variable('DB_PORT', '5432'),
            }
        }
else:
    # SQLite für lokale Entwicklung
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Static files für Production (Render)
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (Uploads)
# https://docs.djangoproject.com/en/5.1/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# SESSION SECURITY
# ============================================================================

# Session-Konfiguration für Sicherheit
SESSION_COOKIE_AGE = 28800  # 8 Stunden (Arbeitstag)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session endet beim Browser-Schließen
SESSION_SAVE_EVERY_REQUEST = True  # Session bei jeder Anfrage speichern
SESSION_COOKIE_HTTPONLY = True  # JavaScript kann nicht auf Session-Cookie zugreifen
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF-Schutz

# Erweiterte Session-Sicherheit
SESSION_COOKIE_NAME = 'adeatools_sessionid'  # Eindeutiger Cookie-Name
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Datenbank-basierte Sessions
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'  # JSON-Serialisierung

# CSRF-Schutz
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = True  # CSRF-Token in Session statt Cookie

# ============================================================================
# PASSWORD SECURITY
# ============================================================================

# Password-Validatoren sind bereits aktiv (Zeilen 95-108)
# Zusätzliche Sicherheit:
PASSWORD_RESET_TIMEOUT = 3600  # 1 Stunde für Passwort-Reset-Links

# ============================================================================
# E-MAIL CONFIGURATION (Optional)
# ============================================================================

# Für lokale Entwicklung: E-Mail wird in Konsole ausgegeben
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Für Production: Konfiguriere SMTP-Server (z.B. Microsoft 365)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = get_env_variable('EMAIL_HOST', 'smtp.office365.com')
# EMAIL_PORT = int(get_env_variable('EMAIL_PORT', '587'))
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = get_env_variable('EMAIL_HOST_USER', '')
# EMAIL_HOST_PASSWORD = get_env_variable('EMAIL_HOST_PASSWORD', '')
# DEFAULT_FROM_EMAIL = get_env_variable('DEFAULT_FROM_EMAIL', 'noreply@adea-treuhand.ch')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'adealohn.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'adealohn': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'adeacore': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
